Repository AutomatedLab/AutomatedLab, pull requests merged in 2020-12, with the labels that each got.

#1034 Fix processor count on multi-processor systems
  AutomatedLabDefinition/AutomatedLabDefinition.psm1
  CHANGELOG.md
Labels: Abandoned

#1038 Making 'FailoverStorage' deployment a separate install option
  AutomatedLab/AutomatedLab.psm1
  AutomatedLab/AutomatedLabFailover.psm1
  CHANGELOG.md
Labels: Enhancement

#1043 Increased speed of Get-LabAzureLabSourcesContent
  AutomatedLab/AutomatedLabAzure.psm1
  AutomatedLabDefinition/AutomatedLabDefinition.psm1
  CHANGELOG.md
Labels: Azure, Enhancement

#1048 Added two new validators
  CHANGELOG.md
  LabXml/Validator/Network/DuplicateAddressAssigned.cs
  LabXml/Validator/Network/NonExistingDnsServerAssigned.cs
Labels: Enhancement

#1058 Only the first 10 disks were initialized
  AutomatedLabWorker/AutomatedLabAzureWorkerVirtualMachines.psm1
  AutomatedLabWorker/AutomatedLabWorkerVirtualMachines.psm1
  CHANGELOG.md
Labels: Bug

#1059 Drives with underscores and hyphens have not been named correctly
  AutomatedLabWorker/AutomatedLabWorkerVirtualMachines.psm1
  CHANGELOG.md
Labels: Bug

#1050 Issue1033
  .build/psake.ps1
  AutomatedLab/AutomatedLabFailover.psm1
  AutomatedLab/AutomatedLabRemoting.psm1
  AutomatedLab/AutomatedLabScvmm.psm1
  CHANGELOG.md
  Help/Wiki/Roles/failoverclustering.md
  Installer/Product.wxs
  LabSources/SampleScripts/Scenarios/Failover Clustering 1.ps1
  LabSources/SampleScripts/Scenarios/Failover Clustering 2 (Shared Storage).ps1
  LabSources/SampleScripts/Scenarios/Failover Clustering 3 MultipleNetworks.ps1
  LabSources/SampleScripts/Scenarios/Failover Clustering 3 MultipleNetworksAzure.ps1
  Tests/Integration/Get-LabConfigurationItem.tests.ps1
  appveyor.yml
Labels: Abandoned
