Repository AutomatedLab/AutomatedLab, pull requests merged in 2020-07, with the labels that each got.

#968 Fixed error handling for Azure
  AutomatedLab/AutomatedLabVirtualMachines.psm1
  CHANGELOG.md
Labels: Bug

#971 LabSources can now be in SD cards or USB memory sticks
  AutomatedLab/AutomatedLabInternals.psm1
  CHANGELOG.md
Labels: Enhancement

#972 Install-LabRdsCertificate works also for 2012R2 now
  AutomatedLab/AutomatedLabRemoting.psm1
  CHANGELOG.md
Labels: Azure, Bug, Hyper-V

#966 Issue23
  AutomatedLab/AutomatedLab.psm1
  AutomatedLab/AutomatedLabHyperV.psm1
  AutomatedLab/AutomatedLabNetwork.psm1
  AutomatedLab/AutomatedLabRemoting.psm1
  AutomatedLab/AutomatedLabVirtualMachines.psm1
  AutomatedLabDefinition/AutomatedLabDefinition.psm1
  AutomatedLabDefinition/AutomatedLabDefinitionNetwork.psm1
  AutomatedLabTest/internal/tests/HyperV.tests.ps1
  AutomatedLabWorker/AutomatedLabAzureWorkerNetwork.psm1
  AutomatedLabWorker/AutomatedLabAzureWorkerVirtualMachines.psm1
  AutomatedLabWorker/AutomatedLabWorkerNetwork.psm1
  AutomatedLabWorker/AutomatedLabWorkerVirtualMachines.psm1
  CHANGELOG.md
  Help/Wiki/About/telemetry.md
  Help/Wiki/Advanced/automatedlabconfig.md
  Help/Wiki/Advanced/connectlabs.md
  Help/Wiki/Advanced/customroles.md
  Help/Wiki/Advanced/notifications.md
  Help/Wiki/Advanced/resourcenaming.md
  Help/Wiki/Advanced/usedsc.md
  Help/Wiki/Basic/addazuresubscription.md
  Help/Wiki/Basic/addmachines.md
  Help/Wiki/Basic/createnewlab.md
  Help/Wiki/Basic/exchangedata.md
  Help/Wiki/Basic/fullyoffline.md
  Help/Wiki/Basic/gettingstarted.md
  Help/Wiki/Basic/install.md
  Help/Wiki/Basic/installsoftware.md
  Help/Wiki/Basic/installwindowsfeatures.md
  Help/Wiki/Basic/invokelabcommand.md
  Help/Wiki/Basic/joindomain.md
  Help/Wiki/Basic/mountazureisos.md
  Help/Wiki/Basic/networksandaddresses.md
  Help/Wiki/Basic/synclabsources.md
  Help/Wiki/Basic/useazurebastion.md
  LabSources/CustomRoles/LabBuilder/HostStart.ps1
  LabXml/Azure/AzureConnectionInfo.cs
  LabXml/Machines/Machine.cs
  LabXml/Network/VirtualNetwork.cs
  LabXml/Validator/Network/HyperV Network/DuplicateAdapterAddressSpace.cs
  LabXml/Validator/Network/HyperV Network/ExternalSwitchNetworkAdapterExists.cs
  mkdocs.yml
Labels: Azure, Enhancement, Hyper-V

#981 Additional tests added
  .build/afterdeploy.ps1
  AutomatedLab/AutomatedLab.init.ps1
  AutomatedLab/AutomatedLab.psd1
  AutomatedLab/AutomatedLab.psm1
  AutomatedLab/AutomatedLabDsc.psm1
  AutomatedLab/AutomatedLabSharePoint.psm1
  AutomatedLab/AutomatedLabTfs.psm1
  AutomatedLabTest/AutomatedLabTest.psd1
  AutomatedLabTest/functions/Invoke-LabPester.ps1
  AutomatedLabTest/internal/tests/ADFS.tests.ps1
  AutomatedLabTest/internal/tests/ADFSProxy.tests.ps1
  AutomatedLabTest/internal/tests/ADFSWAP.tests.ps1
  AutomatedLabTest/internal/tests/AzDevOps.tests.ps1
  AutomatedLabTest/internal/tests/CaRoot.tests.ps1
  AutomatedLabTest/internal/tests/CaSubordinate.tests.ps1
  AutomatedLabTest/internal/tests/DC.tests.ps1
  AutomatedLabTest/internal/tests/DHCP.tests.ps1
  AutomatedLabTest/internal/tests/DSCPullServer.tests.ps1
  AutomatedLabTest/internal/tests/FailoverNode.tests.ps1
  AutomatedLabTest/internal/tests/FailoverStorage.tests.ps1
  AutomatedLabTest/internal/tests/FileServer.tests.ps1
  AutomatedLabTest/internal/tests/FirstChildDC.tests.ps1
  AutomatedLabTest/internal/tests/HyperV.tests.ps1
  AutomatedLabTest/internal/tests/Office2013.tests.ps1
  AutomatedLabTest/internal/tests/Office2016.tests.ps1
  AutomatedLabTest/internal/tests/Orchestrator2012.tests.ps1
  AutomatedLabTest/internal/tests/RootDC.tests.ps1
  AutomatedLabTest/internal/tests/Routing.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2008.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2008R2.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2012.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2014.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2016.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2017.tests.ps1
  AutomatedLabTest/internal/tests/SQLServer2019.tests.ps1
  AutomatedLabTest/internal/tests/SharePoint2013.tests.ps1
  AutomatedLabTest/internal/tests/SharePoint2016.tests.ps1
  AutomatedLabTest/internal/tests/SharePoint2019.tests.ps1
  AutomatedLabTest/internal/tests/Tfs2015.tests.ps1
  AutomatedLabTest/internal/tests/Tfs2017.tests.ps1
  AutomatedLabTest/internal/tests/Tfs2018.tests.ps1
  AutomatedLabTest/internal/tests/TfsBuildWorker.tests.ps1
  AutomatedLabTest/internal/tests/VisualStudio2013.tests.ps1
  AutomatedLabTest/internal/tests/VisualStudio2015.tests.ps1
  AutomatedLabTest/internal/tests/WebServer.tests.ps1
  AutomatedLabTest/internal/tests/WindowsAdminCenter.tests.ps1
  AutomatedLabTest/xml/AutomatedLabTest.Types.ps1xml
  Help/Wiki/Basic/createnewlab.md
  Help/Wiki/Roles/sharepoint.md
  LabSources/PostInstallationActivities/SetupDscPullServer/CreateDscSqlDatabase.ps1
  Tests/Integration/Get-LabConfigurationItem.tests.ps1
Labels: Enhancement
