Repository AutomatedLab/AutomatedLab, pull requests merged in 2020-06, with the labels that each got.

#923 Fix DSC scoping issue #561
  AutomatedLab/AutomatedLabDsc.psm1
  CHANGELOG.md
Labels: Bug

#947 New-LabReleasePipeline and Get-LabTfsFeed on Azure fixed
  AutomatedLab/AutomatedLabTfs.psm1
Labels: Azure, Bug

#953 Net Adapter Pattern fixed
  AutomatedLabWorker/AutomatedLabWorkerNetwork.psm1
Labels: Bug, Hyper-V

#957 Added wildcard support and a filter parameter for 'Get-LabVM'
  AutomatedLab/AutomatedLabVirtualMachines.psm1
Labels: Enhancement
